### ISSUE TITLE
encode-alist sometimes fails with strings as the car of an alist element

### ISSUE THREAD

**Issue by dfmorrison** [hanshuebner/yason#34]
This is in yason 0.7.5 under CCL

    ? (format t "~@{~A~%~}"
            (asdf:component-version (asdf:find-system :yason))
            (lisp-implementation-type)
            (lisp-implementation-version)
            (software-type)
            (software-version)
            (machine-type)
            (machine-version))
    0.7.5
    Clozure Common Lisp
    Version 1.10-r16196  (LinuxX8664)
    Linux
    3.16.0-50-generic
    x86_64
    Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz
    NIL

The following works fine:

    ? (yason:encode-alist '((:symbol . 0) ("string" . 0)))
    {"SYMBOL":0,"string":0}
    ((:SYMBOL . 0) ("string" . 0))

However, if we reorder the two items in the a-list, it signals an error:

    ? (yason:encode-alist '(("string" . 0) (:symbol . 0)))
    [["string"
    > Error: The value 0 is not of the expected type LIST.
    > While executing: YASON::ENCODE-LIST%, in process listener(1).

**Comment by hanshuebner** [comment]
I have removed a set of contributed changes that I did not review carefully enough and that caused this issue.  The removed change set was also not documented very well so I am not sure what is now missing.

**Comment by hanshuebner** [comment]
(Release 0.7.6 has the buggy change set removed)

**Comment by dfmorrison** [comment]
On Tue, Jan 26, 2016 at 6:01 AM, Hans Hübner <notifications@github.com>
wrote:
> I have removed a set of contributed changes that I did not review
> carefully enough and that caused this issue. The removed change set
> was also not documented very well so I am not sure what is now
> missing.

Many thanks for the extremely prompt reply and resolution of this. It does
indeed appear to fix the example I provided.

However, slightly more complex examples using encode-alist seem still to
fail. I have submitted a new issue on GitHub documenting an example.




-- 
Don Morrison <dfm2@cmu.edu>
"The obvious mathematical breakthrough would be development of
an easy way to factor large prime numbers."
    -- Bill Gates, _The Road Ahead_ (original 1995 hardcover edition)

**Comment by rick-monster** [comment]
In my defence, the patch I submitted *does* enable a neat bijection between JSON and arbitrarily nested alist/plist-encoded s-expressions.  This is at the expense of being able to use strings as alist keys.

My judgement was the nested behaviour is far more useful & common than string-as-alist-key, especially for plists (because they are built-in to CL's function arguments).  I do apologise if that wasn't clear from commit messages and the updates I made to documentation that this compromise was inherent in my solution.

I will try and hack on it in case there some way I missed to represent complex nested JSON objects as alist/plist without sacrificing string-as-alist-key.  But IIRC it's an either or...

**Comment by dfmorrison** [comment]
Thanks for the explanation.

Three points, however:

1. Even if that neat bijection did work, it would be problematic since `(parse <mumble> :object-as :alist)` decodes keys as strings, and thus prohibiting their use when encoding means yason can't re-encode what it decodes with its out-of-the-box settings.

2. I think your characterization of "at the expense of being able to use strings as alist keys" is a little too weak. If I understand the code correctly, were it working as intended you would only be able to use keywords as keys, and thus be unable to use symbols interned in some other package, or other items comparable with eq, as keys.

3. But further, I don't think it does work. Here's an example, using the version of yason before the patch was rescinded. Note that even though keywords, and not strings, are being used as keys, it still blows up.

    ```   
    ? (load (merge-pathnames "test.lisp" (asdf:system-source-directory :yason)))
    '#P"/home/dfm/common-lisp/yason/test.lisp"

    ?  (asdf:component-version (asdf:find-system :yason))
    "0.7.5"

    ?  yason-test::*basic-test-json-string*
    "[{\"foo\":1,\"bar\":[7,8,9]},2,3,4,[5,6,7],true,null]"

    ? (yason:parse yason-test::*basic-test-json-string*
                 :object-key-fn #'(lambda (x)
                                    (intern (string-upcase x)
                                            :keyword))
                 :object-as :alist)
    (((:BAR 7 8 9) (:FOO . 1)) 2 3 4 (5 6 7) T NIL)

    ? (yason:encode-alist *)
    {
    > Error: The value (:BAR 7 8 9) is not of the expected type (OR STRING SYMBOL CHARACTER).
    > While executing: STRING, in process listener(1).
    > Type :POP to abort, :R for a list of available restarts.
    > Type :? for other options.
    1 > 
    ```

**Comment by rick-monster** [comment]
So in response to your points:

1. I originally wanted to change the out-of the box behaviour in order to emphasise the potential for a bijection, but @hanshuebner did not want to break the api.  So I guess what eventually got merged is a bad compromise.
2. you are correct - s/strings/non-keywords/. In the context of alists I guess this breaks many people's 'canonical' usage.  My own use-cases were all *plist* based (where enforcing keywords makes more sense).  It was stupid to touch the alist behaviour at all...
3. just ran the same roundtrip test on both my old HEAD from original pull request and on 0.7.5. This is on sbcl 1.3.1 on 64 bit linux.  Can't reproduce the error and *can* round-trip that gob of easier JSON edge-cases through either my alist or plist lisp representation (I don't mind vertical bars so there's no #'string-upcase)

```
CL-USER> (asdf:component-version (asdf:find-system :yason))
"0.7.5"

CL-USER> (yason:encode-alist
	  (yason:parse "[{\"foo\":1,\"bar\":[7,8,9]},2,3,4,[5,6,7],true,null]"
		       :object-key-fn #'(lambda (x)
					  (intern x :keyword))
		       :object-as :alist))
[{"foo":1,"bar":[7,8,9]},2,3,4,[5,6,7],true,null]
(((:|foo| . 1) (:|bar| 7 8 9)) 2 3 4 (5 6 7) T NIL)

CL-USER> (yason:encode-plist
	  (yason:parse "[{\"foo\":1,\"bar\":[7,8,9]},2,3,4,[5,6,7],true,null]"
		       :object-key-fn #'(lambda (x)
					  (intern x :keyword))
		       :object-as :plist))
[{"foo":1,"bar":[7,8,9]},2,3,4,[5,6,7],true,null]
((:|foo| 1 :|bar| (7 8 9)) 2 3 4 (5 6 7) T NIL)
```

**Comment by dfmorrison** [comment]
Well, this is certainly interesting. It (that is, your a-list example, run in 0.7.5) works for me in SBCL and CLISP, but fails in CCL. I guess a next step is I'll upgrade from CCL 1.10 to 1.11 and see if that changes anything, and otherwise try to track down why the behavior differs.

**Comment by dfmorrison** [comment]
Turns out upgrading CCL to 1.11 seems to have solved this. Wow. Looking at the release notes for CCL 1.11 it's hard to see what the problem must have been.
