### ISSUE TITLE
Parse JSON object as CLOS class 

### ISSUE THREAD

**Issue by HenryS1** [hanshuebner/yason#38]
I might be missing something, but I couldn't see a way to parse a JSON object as a CLOS class.

If there isn't then perhaps it could be generated when defining the encoder using macros.

**Comment by hanshuebner** [comment]
YASON does not have a mapping between CLOS and JSON objects.  The reason why that is so is that such a mapping would generally have to prescribe a certain way to map, and the _right_ way to map depends on the application at hand.  Writing your own mapping to your liking is not that hard, though, and it can be done in several ways - Using macros, or using CLOS and application specific slot options.  I have done both, but in application specific ways.  I like that approach because such mappings can then restrict themselves to the needs of the application and don't need to be covering any other cases.  This allows them to be minimal enough to be part of the application rather than part of the JSON encoding system.

CL-JSON takes another approach which may be more to your liking.

**Comment by gschjetne** [comment]
@HenryS1 if you mean mapping JSON objects to CLOS slots, I wrote [json-mop](https://github.com/gschjetne/json-mop) to do just that, but it might not always be a good idea, since it exposes the internal implementation of your classes, making them difficult to change without breaking whatever external API you use your JSON for. You pay for the convenience by sacrificing some of the power of CLOS.

**Comment by HenryS1** [comment]
Thanks @gschjetne I'll check it out.
